### ISSUE TITLE
GaviotaTbCache UCI option causes crashes

### ISSUE THREAD

**Issue by tpoppins** [gekomad/Cinnamon#44]
Setting this option -- either manually, with _setoption name GaviotaTbCache value 32_ or via a GUI (Cute Chess) causes a crash, apparently due to an access violation, on Windows 7 x64 Pro SP1. Here's the WER report:

```
Version=1
EventType=APPCRASH
EventTime=131981553443724811
ReportType=2
Consent=1
UploadTime=131981553445234898
ReportIdentifier=478ca2fd-5079-11e9-a1cf-002713cab278
IntegratorReportIdentifier=478ca2fc-5079-11e9-a1cf-002713cab278
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=cinnamon_2.1_x64-INTEL.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=00000000
Sig[3].Name=Fault Module Name
Sig[3].Value=cinnamon_2.1_x64-INTEL.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000033d05
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0615
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0615d2e5252921b836461fa76ec7cdfd
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=7847
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=78471eb7bee1e1fe46d77ab953aeca5c
UI[2]=C:\Program Files\ChessBase\Engines.x64\CCRL\a-c\cinnamon\cinnamon_2.1_x64-INTEL.exe
UI[3]=cinnamon_2.1_x64-INTEL.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\ChessBase\Engines.x64\CCRL\a-c\cinnamon\cinnamon_2.1_x64-INTEL.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\msvcrt.dll
LoadedModule[5]=C:\Windows\system32\USER32.dll
LoadedModule[6]=C:\Windows\system32\GDI32.dll
LoadedModule[7]=C:\Windows\system32\LPK.dll
LoadedModule[8]=C:\Windows\system32\USP10.dll
LoadedModule[9]=C:\Windows\system32\IMM32.DLL
LoadedModule[10]=C:\Windows\system32\MSCTF.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=cinnamon_2.1_x64-INTEL.exe
AppPath=C:\Program Files\ChessBase\Engines.x64\CCRL\a-c\cinnamon\cinnamon_2.1_x64-INTEL.exe

```

According to a Cute Chess developer, setting this option via Cute Chess CLI (presumably under Linux) results in a segmentation fault: [link](https://github.com/cutechess/cutechess/issues/405#issuecomment-412264047). Although the version discussed in that thread is 2.0, same problem is present in v2.1.

Hiding this option from the GUI (e.g. by hex-editing the exec to change "option name GaviotaTbCache" to "**x**ption name GaviotaTbCache", or suppressing the command with adapter InBetween) allows Cinnamon to run under Cute Chess. There are still several other problems, so I think it's best to create a new issue for each one separately.

**Comment by gekomad** [comment]
Hi tpoppins and many thanks for you debug

I fixed #44 and #45 issues

https://github.com/gekomad/Cinnamon/issues/44
https://github.com/gekomad/Cinnamon/issues/45

If you may do the test again I'd appreciate

the exe is here http://cinnamonchess.altervista.org/cinnamon_2.2_beta.exe

thanks
Giuseppe Cannella

**Comment by tpoppins** [comment]
Amazing! I'd never seen bugs fixed so quickly. Thank you, Giuseppe.

Indeed, the beta exec now runs without having to resort to tricks. I'll close this issue and proceed to #45 which appears not completely solved still.

**Comment by gekomad** [comment]
do you have a "file not found" yet?

my test is ok:

setoption name GaviotaTbPath value c:\chess
No 3-pc TBs available
No 4-pc TBs available
No 5-pc TBs available

**Comment by gekomad** [comment]
Hi @tpoppins I released version 2.2a

**Comment by tpoppins** [comment]
Thank you for the headsup, Giuseppe, we'll have it tested at 40/4 this week.

BTW, one of our testers did a 300+ blitz gauntlet with v2.1 under the Arena GUI and reported ~60 losses on time. I did my own short test of 200 games with the hashfix beta of 2.2 you posted in #46 and there was not a single abnormal termination on Cinnamon's part -- no forfeits, stalls or disconnects. I hope the official version performs as cleanly as that.
